# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetDedicatedInferenceSizesResult',
    'AwaitableGetDedicatedInferenceSizesResult',
    'get_dedicated_inference_sizes',
    'get_dedicated_inference_sizes_output',
]

@pulumi.output_type
class GetDedicatedInferenceSizesResult:
    """
    A collection of values returned by getDedicatedInferenceSizes.
    """
    def __init__(__self__, enabled_regions=None, id=None, sizes=None):
        if enabled_regions and not isinstance(enabled_regions, list):
            raise TypeError("Expected argument 'enabled_regions' to be a list")
        pulumi.set(__self__, "enabled_regions", enabled_regions)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if sizes and not isinstance(sizes, list):
            raise TypeError("Expected argument 'sizes' to be a list")
        pulumi.set(__self__, "sizes", sizes)

    @_builtins.property
    @pulumi.getter(name="enabledRegions")
    def enabled_regions(self) -> Sequence[_builtins.str]:
        """
        The list of region slugs where dedicated inference endpoints can be deployed.
        """
        return pulumi.get(self, "enabled_regions")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def sizes(self) -> Sequence['outputs.GetDedicatedInferenceSizesSizeResult']:
        """
        The list of available GPU sizes. Each element contains:
        """
        return pulumi.get(self, "sizes")


class AwaitableGetDedicatedInferenceSizesResult(GetDedicatedInferenceSizesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDedicatedInferenceSizesResult(
            enabled_regions=self.enabled_regions,
            id=self.id,
            sizes=self.sizes)


def get_dedicated_inference_sizes(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDedicatedInferenceSizesResult:
    """
    Returns the available GPU sizes and their configurations for dedicated inference
    endpoints, including pricing, hardware specifications, and region availability.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_digitalocean as digitalocean

    available = digitalocean.get_dedicated_inference_sizes()
    pulumi.export("enabledRegions", available.enabled_regions)
    pulumi.export("sizes", available.sizes)
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('digitalocean:index/getDedicatedInferenceSizes:getDedicatedInferenceSizes', __args__, opts=opts, typ=GetDedicatedInferenceSizesResult).value

    return AwaitableGetDedicatedInferenceSizesResult(
        enabled_regions=pulumi.get(__ret__, 'enabled_regions'),
        id=pulumi.get(__ret__, 'id'),
        sizes=pulumi.get(__ret__, 'sizes'))
def get_dedicated_inference_sizes_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetDedicatedInferenceSizesResult]:
    """
    Returns the available GPU sizes and their configurations for dedicated inference
    endpoints, including pricing, hardware specifications, and region availability.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_digitalocean as digitalocean

    available = digitalocean.get_dedicated_inference_sizes()
    pulumi.export("enabledRegions", available.enabled_regions)
    pulumi.export("sizes", available.sizes)
    ```
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('digitalocean:index/getDedicatedInferenceSizes:getDedicatedInferenceSizes', __args__, opts=opts, typ=GetDedicatedInferenceSizesResult)
    return __ret__.apply(lambda __response__: GetDedicatedInferenceSizesResult(
        enabled_regions=pulumi.get(__response__, 'enabled_regions'),
        id=pulumi.get(__response__, 'id'),
        sizes=pulumi.get(__response__, 'sizes')))
