// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package digitalocean

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-digitalocean/sdk/v4/go/digitalocean/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Deprecated: digitalocean.getGenaiIndexingJobDataSources has been deprecated in favor of digitalocean.getGradientaiIndexingJobDataSources
func GetGenaiIndexingJobDataSources(ctx *pulumi.Context, args *GetGenaiIndexingJobDataSourcesArgs, opts ...pulumi.InvokeOption) (*GetGenaiIndexingJobDataSourcesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetGenaiIndexingJobDataSourcesResult
	err := ctx.Invoke("digitalocean:index/getGenaiIndexingJobDataSources:getGenaiIndexingJobDataSources", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getGenaiIndexingJobDataSources.
type GetGenaiIndexingJobDataSourcesArgs struct {
	IndexingJobUuid string `pulumi:"indexingJobUuid"`
}

// A collection of values returned by getGenaiIndexingJobDataSources.
type GetGenaiIndexingJobDataSourcesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id                 string                                            `pulumi:"id"`
	IndexedDataSources []GetGenaiIndexingJobDataSourcesIndexedDataSource `pulumi:"indexedDataSources"`
	IndexingJobUuid    string                                            `pulumi:"indexingJobUuid"`
}

func GetGenaiIndexingJobDataSourcesOutput(ctx *pulumi.Context, args GetGenaiIndexingJobDataSourcesOutputArgs, opts ...pulumi.InvokeOption) GetGenaiIndexingJobDataSourcesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetGenaiIndexingJobDataSourcesResultOutput, error) {
			args := v.(GetGenaiIndexingJobDataSourcesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("digitalocean:index/getGenaiIndexingJobDataSources:getGenaiIndexingJobDataSources", args, GetGenaiIndexingJobDataSourcesResultOutput{}, options).(GetGenaiIndexingJobDataSourcesResultOutput), nil
		}).(GetGenaiIndexingJobDataSourcesResultOutput)
}

// A collection of arguments for invoking getGenaiIndexingJobDataSources.
type GetGenaiIndexingJobDataSourcesOutputArgs struct {
	IndexingJobUuid pulumi.StringInput `pulumi:"indexingJobUuid"`
}

func (GetGenaiIndexingJobDataSourcesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGenaiIndexingJobDataSourcesArgs)(nil)).Elem()
}

// A collection of values returned by getGenaiIndexingJobDataSources.
type GetGenaiIndexingJobDataSourcesResultOutput struct{ *pulumi.OutputState }

func (GetGenaiIndexingJobDataSourcesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGenaiIndexingJobDataSourcesResult)(nil)).Elem()
}

func (o GetGenaiIndexingJobDataSourcesResultOutput) ToGetGenaiIndexingJobDataSourcesResultOutput() GetGenaiIndexingJobDataSourcesResultOutput {
	return o
}

func (o GetGenaiIndexingJobDataSourcesResultOutput) ToGetGenaiIndexingJobDataSourcesResultOutputWithContext(ctx context.Context) GetGenaiIndexingJobDataSourcesResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetGenaiIndexingJobDataSourcesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetGenaiIndexingJobDataSourcesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetGenaiIndexingJobDataSourcesResultOutput) IndexedDataSources() GetGenaiIndexingJobDataSourcesIndexedDataSourceArrayOutput {
	return o.ApplyT(func(v GetGenaiIndexingJobDataSourcesResult) []GetGenaiIndexingJobDataSourcesIndexedDataSource {
		return v.IndexedDataSources
	}).(GetGenaiIndexingJobDataSourcesIndexedDataSourceArrayOutput)
}

func (o GetGenaiIndexingJobDataSourcesResultOutput) IndexingJobUuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetGenaiIndexingJobDataSourcesResult) string { return v.IndexingJobUuid }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetGenaiIndexingJobDataSourcesResultOutput{})
}
