// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package digitalocean

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-digitalocean/sdk/v4/go/digitalocean/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// Get the reserved IPv6:
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-digitalocean/sdk/v4/go/digitalocean"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			foo, err := digitalocean.NewReservedIpv6(ctx, "foo", &digitalocean.ReservedIpv6Args{
//				RegionSlug: pulumi.String("nyc3"),
//			})
//			if err != nil {
//				return err
//			}
//			_ = digitalocean.LookupReservedIpv6Output(ctx, digitalocean.GetReservedIpv6OutputArgs{
//				Ip: foo.Ip,
//			}, nil)
//			return nil
//		})
//	}
//
// ```
func LookupReservedIpv6(ctx *pulumi.Context, args *LookupReservedIpv6Args, opts ...pulumi.InvokeOption) (*LookupReservedIpv6Result, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupReservedIpv6Result
	err := ctx.Invoke("digitalocean:index/getReservedIpv6:getReservedIpv6", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getReservedIpv6.
type LookupReservedIpv6Args struct {
	// The allocated IPv6 address of the specific reserved IPv6 to retrieve.
	Ip string `pulumi:"ip"`
}

// A collection of values returned by getReservedIpv6.
type LookupReservedIpv6Result struct {
	// The Droplet id that the reserved IP has been assigned to.
	DropletId int `pulumi:"dropletId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	Ip string `pulumi:"ip"`
	// The region that the reserved IPv6 is reserved to.
	RegionSlug string `pulumi:"regionSlug"`
	// The uniform resource name of the reserved IPv6.
	Urn string `pulumi:"urn"`
}

func LookupReservedIpv6Output(ctx *pulumi.Context, args LookupReservedIpv6OutputArgs, opts ...pulumi.InvokeOption) LookupReservedIpv6ResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupReservedIpv6ResultOutput, error) {
			args := v.(LookupReservedIpv6Args)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("digitalocean:index/getReservedIpv6:getReservedIpv6", args, LookupReservedIpv6ResultOutput{}, options).(LookupReservedIpv6ResultOutput), nil
		}).(LookupReservedIpv6ResultOutput)
}

// A collection of arguments for invoking getReservedIpv6.
type LookupReservedIpv6OutputArgs struct {
	// The allocated IPv6 address of the specific reserved IPv6 to retrieve.
	Ip pulumi.StringInput `pulumi:"ip"`
}

func (LookupReservedIpv6OutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupReservedIpv6Args)(nil)).Elem()
}

// A collection of values returned by getReservedIpv6.
type LookupReservedIpv6ResultOutput struct{ *pulumi.OutputState }

func (LookupReservedIpv6ResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupReservedIpv6Result)(nil)).Elem()
}

func (o LookupReservedIpv6ResultOutput) ToLookupReservedIpv6ResultOutput() LookupReservedIpv6ResultOutput {
	return o
}

func (o LookupReservedIpv6ResultOutput) ToLookupReservedIpv6ResultOutputWithContext(ctx context.Context) LookupReservedIpv6ResultOutput {
	return o
}

// The Droplet id that the reserved IP has been assigned to.
func (o LookupReservedIpv6ResultOutput) DropletId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupReservedIpv6Result) int { return v.DropletId }).(pulumi.IntOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupReservedIpv6ResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupReservedIpv6Result) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupReservedIpv6ResultOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v LookupReservedIpv6Result) string { return v.Ip }).(pulumi.StringOutput)
}

// The region that the reserved IPv6 is reserved to.
func (o LookupReservedIpv6ResultOutput) RegionSlug() pulumi.StringOutput {
	return o.ApplyT(func(v LookupReservedIpv6Result) string { return v.RegionSlug }).(pulumi.StringOutput)
}

// The uniform resource name of the reserved IPv6.
func (o LookupReservedIpv6ResultOutput) Urn() pulumi.StringOutput {
	return o.ApplyT(func(v LookupReservedIpv6Result) string { return v.Urn }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupReservedIpv6ResultOutput{})
}
