provider: digitalocean
major-version: 4
esc:
    enabled: true
env:
    DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
