provider: digitalocean
major-version: 4
esc:
  enabled: true
env:
  DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
makeTemplate: bridged
plugins:
  - name: kubernetes
    version: "4.11.0"
  - name: std
    version: "1.6.2"
  - name: terraform
    version: "1.0.17"
    kind: converter
team: ecosystem
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
