provider: digitalocean
major-version: 4
env:
  DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
makeTemplate: bridged
plugins:
  - name: kubernetes
    version: "4.11.0"
  - name: std
    version: "1.6.2"
  - name: terraform
    version: "1.0.17"
    kind: converter
team: ecosystem
pulumiConvert: 1
registryDocs: true
actions:
  preTest:
    - name: make upstream
      run: |
        make upstream
    - name: Run provider tests
      run: |
        cd provider && go test -v -json -count=1 -cover -timeout 2h -tags=${{ matrix.language }} -parallel 4 . 2>&1 | tee /tmp/gotest.log | gotestfmt
