// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOcean
{
    public static class GetDropletAutoscale
    {
        /// <summary>
        /// Get information on a Droplet Autoscale pool for use with other managed resources. This datasource provides all the
        /// Droplet Autoscale pool properties as configured on the DigitalOcean account. This is useful if the Droplet Autoscale 
        /// pool in question is not managed by Terraform, or any of the relevant data would need to referenced in other managed 
        /// resources.
        /// 
        /// ## Example Usage
        /// 
        /// Get the Droplet Autoscale pool by name:
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DigitalOcean = Pulumi.DigitalOcean;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var my_imported_autoscale_pool = DigitalOcean.GetDropletAutoscale.Invoke(new()
        ///     {
        ///         Name = my_existing_autoscale_pool.Name,
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// Get the Droplet Autoscale pool by ID:
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DigitalOcean = Pulumi.DigitalOcean;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var my_imported_autoscale_pool = DigitalOcean.GetDropletAutoscale.Invoke(new()
        ///     {
        ///         Id = my_existing_autoscale_pool.Id,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetDropletAutoscaleResult> InvokeAsync(GetDropletAutoscaleArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDropletAutoscaleResult>("digitalocean:index/getDropletAutoscale:getDropletAutoscale", args ?? new GetDropletAutoscaleArgs(), options.WithDefaults());

        /// <summary>
        /// Get information on a Droplet Autoscale pool for use with other managed resources. This datasource provides all the
        /// Droplet Autoscale pool properties as configured on the DigitalOcean account. This is useful if the Droplet Autoscale 
        /// pool in question is not managed by Terraform, or any of the relevant data would need to referenced in other managed 
        /// resources.
        /// 
        /// ## Example Usage
        /// 
        /// Get the Droplet Autoscale pool by name:
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DigitalOcean = Pulumi.DigitalOcean;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var my_imported_autoscale_pool = DigitalOcean.GetDropletAutoscale.Invoke(new()
        ///     {
        ///         Name = my_existing_autoscale_pool.Name,
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// Get the Droplet Autoscale pool by ID:
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DigitalOcean = Pulumi.DigitalOcean;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var my_imported_autoscale_pool = DigitalOcean.GetDropletAutoscale.Invoke(new()
        ///     {
        ///         Id = my_existing_autoscale_pool.Id,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetDropletAutoscaleResult> Invoke(GetDropletAutoscaleInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDropletAutoscaleResult>("digitalocean:index/getDropletAutoscale:getDropletAutoscale", args ?? new GetDropletAutoscaleInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Get information on a Droplet Autoscale pool for use with other managed resources. This datasource provides all the
        /// Droplet Autoscale pool properties as configured on the DigitalOcean account. This is useful if the Droplet Autoscale 
        /// pool in question is not managed by Terraform, or any of the relevant data would need to referenced in other managed 
        /// resources.
        /// 
        /// ## Example Usage
        /// 
        /// Get the Droplet Autoscale pool by name:
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DigitalOcean = Pulumi.DigitalOcean;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var my_imported_autoscale_pool = DigitalOcean.GetDropletAutoscale.Invoke(new()
        ///     {
        ///         Name = my_existing_autoscale_pool.Name,
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// Get the Droplet Autoscale pool by ID:
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DigitalOcean = Pulumi.DigitalOcean;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var my_imported_autoscale_pool = DigitalOcean.GetDropletAutoscale.Invoke(new()
        ///     {
        ///         Id = my_existing_autoscale_pool.Id,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetDropletAutoscaleResult> Invoke(GetDropletAutoscaleInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDropletAutoscaleResult>("digitalocean:index/getDropletAutoscale:getDropletAutoscale", args ?? new GetDropletAutoscaleInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDropletAutoscaleArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of Droplet Autoscale pool.
        /// </summary>
        [Input("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The name of Droplet Autoscale pool.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetDropletAutoscaleArgs()
        {
        }
        public static new GetDropletAutoscaleArgs Empty => new GetDropletAutoscaleArgs();
    }

    public sealed class GetDropletAutoscaleInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of Droplet Autoscale pool.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// The name of Droplet Autoscale pool.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetDropletAutoscaleInvokeArgs()
        {
        }
        public static new GetDropletAutoscaleInvokeArgs Empty => new GetDropletAutoscaleInvokeArgs();
    }


    [OutputType]
    public sealed class GetDropletAutoscaleResult
    {
        public readonly ImmutableArray<Outputs.GetDropletAutoscaleConfigResult> Configs;
        public readonly string CreatedAt;
        public readonly ImmutableArray<Outputs.GetDropletAutoscaleCurrentUtilizationResult> CurrentUtilizations;
        public readonly ImmutableArray<Outputs.GetDropletAutoscaleDropletTemplateResult> DropletTemplates;
        public readonly string? Id;
        public readonly string? Name;
        public readonly string Status;
        public readonly string UpdatedAt;

        [OutputConstructor]
        private GetDropletAutoscaleResult(
            ImmutableArray<Outputs.GetDropletAutoscaleConfigResult> configs,

            string createdAt,

            ImmutableArray<Outputs.GetDropletAutoscaleCurrentUtilizationResult> currentUtilizations,

            ImmutableArray<Outputs.GetDropletAutoscaleDropletTemplateResult> dropletTemplates,

            string? id,

            string? name,

            string status,

            string updatedAt)
        {
            Configs = configs;
            CreatedAt = createdAt;
            CurrentUtilizations = currentUtilizations;
            DropletTemplates = dropletTemplates;
            Id = id;
            Name = name;
            Status = status;
            UpdatedAt = updatedAt;
        }
    }
}
