// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.digitalocean.outputs.GetAppSpecServiceLogDestinationDatadog;
import com.pulumi.digitalocean.outputs.GetAppSpecServiceLogDestinationLogtail;
import com.pulumi.digitalocean.outputs.GetAppSpecServiceLogDestinationOpenSearch;
import com.pulumi.digitalocean.outputs.GetAppSpecServiceLogDestinationPapertrail;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetAppSpecServiceLogDestination {
    /**
     * @return Datadog configuration.
     * 
     */
    private @Nullable GetAppSpecServiceLogDestinationDatadog datadog;
    /**
     * @return Logtail configuration.
     * 
     */
    private @Nullable GetAppSpecServiceLogDestinationLogtail logtail;
    /**
     * @return The name of the component.
     * 
     */
    private String name;
    /**
     * @return OpenSearch configuration.
     * 
     */
    private @Nullable GetAppSpecServiceLogDestinationOpenSearch openSearch;
    /**
     * @return Papertrail configuration.
     * 
     */
    private @Nullable GetAppSpecServiceLogDestinationPapertrail papertrail;

    private GetAppSpecServiceLogDestination() {}
    /**
     * @return Datadog configuration.
     * 
     */
    public Optional<GetAppSpecServiceLogDestinationDatadog> datadog() {
        return Optional.ofNullable(this.datadog);
    }
    /**
     * @return Logtail configuration.
     * 
     */
    public Optional<GetAppSpecServiceLogDestinationLogtail> logtail() {
        return Optional.ofNullable(this.logtail);
    }
    /**
     * @return The name of the component.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return OpenSearch configuration.
     * 
     */
    public Optional<GetAppSpecServiceLogDestinationOpenSearch> openSearch() {
        return Optional.ofNullable(this.openSearch);
    }
    /**
     * @return Papertrail configuration.
     * 
     */
    public Optional<GetAppSpecServiceLogDestinationPapertrail> papertrail() {
        return Optional.ofNullable(this.papertrail);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAppSpecServiceLogDestination defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable GetAppSpecServiceLogDestinationDatadog datadog;
        private @Nullable GetAppSpecServiceLogDestinationLogtail logtail;
        private String name;
        private @Nullable GetAppSpecServiceLogDestinationOpenSearch openSearch;
        private @Nullable GetAppSpecServiceLogDestinationPapertrail papertrail;
        public Builder() {}
        public Builder(GetAppSpecServiceLogDestination defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.datadog = defaults.datadog;
    	      this.logtail = defaults.logtail;
    	      this.name = defaults.name;
    	      this.openSearch = defaults.openSearch;
    	      this.papertrail = defaults.papertrail;
        }

        @CustomType.Setter
        public Builder datadog(@Nullable GetAppSpecServiceLogDestinationDatadog datadog) {

            this.datadog = datadog;
            return this;
        }
        @CustomType.Setter
        public Builder logtail(@Nullable GetAppSpecServiceLogDestinationLogtail logtail) {

            this.logtail = logtail;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetAppSpecServiceLogDestination", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder openSearch(@Nullable GetAppSpecServiceLogDestinationOpenSearch openSearch) {

            this.openSearch = openSearch;
            return this;
        }
        @CustomType.Setter
        public Builder papertrail(@Nullable GetAppSpecServiceLogDestinationPapertrail papertrail) {

            this.papertrail = papertrail;
            return this;
        }
        public GetAppSpecServiceLogDestination build() {
            final var _resultValue = new GetAppSpecServiceLogDestination();
            _resultValue.datadog = datadog;
            _resultValue.logtail = logtail;
            _resultValue.name = name;
            _resultValue.openSearch = openSearch;
            _resultValue.papertrail = papertrail;
            return _resultValue;
        }
    }
}
