// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetAgentPlatformCustomModelsCustomModelActiveDeploymentEndpoint {
    /**
     * @return Private endpoint FQDN.
     * 
     */
    private String privateEndpointFqdn;
    /**
     * @return Public endpoint FQDN, if enabled.
     * 
     */
    private String publicEndpointFqdn;

    private GetAgentPlatformCustomModelsCustomModelActiveDeploymentEndpoint() {}
    /**
     * @return Private endpoint FQDN.
     * 
     */
    public String privateEndpointFqdn() {
        return this.privateEndpointFqdn;
    }
    /**
     * @return Public endpoint FQDN, if enabled.
     * 
     */
    public String publicEndpointFqdn() {
        return this.publicEndpointFqdn;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAgentPlatformCustomModelsCustomModelActiveDeploymentEndpoint defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String privateEndpointFqdn;
        private String publicEndpointFqdn;
        public Builder() {}
        public Builder(GetAgentPlatformCustomModelsCustomModelActiveDeploymentEndpoint defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.privateEndpointFqdn = defaults.privateEndpointFqdn;
    	      this.publicEndpointFqdn = defaults.publicEndpointFqdn;
        }

        @CustomType.Setter
        public Builder privateEndpointFqdn(String privateEndpointFqdn) {
            if (privateEndpointFqdn == null) {
              throw new MissingRequiredPropertyException("GetAgentPlatformCustomModelsCustomModelActiveDeploymentEndpoint", "privateEndpointFqdn");
            }
            this.privateEndpointFqdn = privateEndpointFqdn;
            return this;
        }
        @CustomType.Setter
        public Builder publicEndpointFqdn(String publicEndpointFqdn) {
            if (publicEndpointFqdn == null) {
              throw new MissingRequiredPropertyException("GetAgentPlatformCustomModelsCustomModelActiveDeploymentEndpoint", "publicEndpointFqdn");
            }
            this.publicEndpointFqdn = publicEndpointFqdn;
            return this;
        }
        public GetAgentPlatformCustomModelsCustomModelActiveDeploymentEndpoint build() {
            final var _resultValue = new GetAgentPlatformCustomModelsCustomModelActiveDeploymentEndpoint();
            _resultValue.privateEndpointFqdn = privateEndpointFqdn;
            _resultValue.publicEndpointFqdn = publicEndpointFqdn;
            return _resultValue;
        }
    }
}
