// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetAppSpecIngressRuleComponent {
    /**
     * @return The name of the component.
     * 
     */
    private String name;
    /**
     * @return An optional flag to preserve the path that is forwarded to the backend service.
     * 
     */
    private Boolean preservePathPrefix;
    private String rewrite;

    private GetAppSpecIngressRuleComponent() {}
    /**
     * @return The name of the component.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return An optional flag to preserve the path that is forwarded to the backend service.
     * 
     */
    public Boolean preservePathPrefix() {
        return this.preservePathPrefix;
    }
    public String rewrite() {
        return this.rewrite;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAppSpecIngressRuleComponent defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String name;
        private Boolean preservePathPrefix;
        private String rewrite;
        public Builder() {}
        public Builder(GetAppSpecIngressRuleComponent defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.preservePathPrefix = defaults.preservePathPrefix;
    	      this.rewrite = defaults.rewrite;
        }

        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        @CustomType.Setter
        public Builder preservePathPrefix(Boolean preservePathPrefix) {
            this.preservePathPrefix = Objects.requireNonNull(preservePathPrefix);
            return this;
        }
        @CustomType.Setter
        public Builder rewrite(String rewrite) {
            this.rewrite = Objects.requireNonNull(rewrite);
            return this;
        }
        public GetAppSpecIngressRuleComponent build() {
            final var _resultValue = new GetAppSpecIngressRuleComponent();
            _resultValue.name = name;
            _resultValue.preservePathPrefix = preservePathPrefix;
            _resultValue.rewrite = rewrite;
            return _resultValue;
        }
    }
}
