// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetAppSpecEgress {
    /**
     * @return The type of the environment variable, `GENERAL` or `SECRET`.
     * 
     */
    private @Nullable String type;

    private GetAppSpecEgress() {}
    /**
     * @return The type of the environment variable, `GENERAL` or `SECRET`.
     * 
     */
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAppSpecEgress defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String type;
        public Builder() {}
        public Builder(GetAppSpecEgress defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder type(@Nullable String type) {

            this.type = type;
            return this;
        }
        public GetAppSpecEgress build() {
            final var _resultValue = new GetAppSpecEgress();
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
