// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.digitalocean.outputs.GetAppSpecJobAlertDestinationsSlackWebhook;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class GetAppSpecJobAlertDestinations {
    private @Nullable List<String> emails;
    private @Nullable List<GetAppSpecJobAlertDestinationsSlackWebhook> slackWebhooks;

    private GetAppSpecJobAlertDestinations() {}
    public List<String> emails() {
        return this.emails == null ? List.of() : this.emails;
    }
    public List<GetAppSpecJobAlertDestinationsSlackWebhook> slackWebhooks() {
        return this.slackWebhooks == null ? List.of() : this.slackWebhooks;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAppSpecJobAlertDestinations defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<String> emails;
        private @Nullable List<GetAppSpecJobAlertDestinationsSlackWebhook> slackWebhooks;
        public Builder() {}
        public Builder(GetAppSpecJobAlertDestinations defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.emails = defaults.emails;
    	      this.slackWebhooks = defaults.slackWebhooks;
        }

        @CustomType.Setter
        public Builder emails(@Nullable List<String> emails) {

            this.emails = emails;
            return this;
        }
        public Builder emails(String... emails) {
            return emails(List.of(emails));
        }
        @CustomType.Setter
        public Builder slackWebhooks(@Nullable List<GetAppSpecJobAlertDestinationsSlackWebhook> slackWebhooks) {

            this.slackWebhooks = slackWebhooks;
            return this;
        }
        public Builder slackWebhooks(GetAppSpecJobAlertDestinationsSlackWebhook... slackWebhooks) {
            return slackWebhooks(List.of(slackWebhooks));
        }
        public GetAppSpecJobAlertDestinations build() {
            final var _resultValue = new GetAppSpecJobAlertDestinations();
            _resultValue.emails = emails;
            _resultValue.slackWebhooks = slackWebhooks;
            return _resultValue;
        }
    }
}
