// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetContainerRegistriesResult {
    private String createdAt;
    private String endpoint;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private String name;
    private String region;
    private String serverUrl;
    private Integer storageUsageBytes;
    private String subscriptionTierSlug;

    private GetContainerRegistriesResult() {}
    public String createdAt() {
        return this.createdAt;
    }
    public String endpoint() {
        return this.endpoint;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String name() {
        return this.name;
    }
    public String region() {
        return this.region;
    }
    public String serverUrl() {
        return this.serverUrl;
    }
    public Integer storageUsageBytes() {
        return this.storageUsageBytes;
    }
    public String subscriptionTierSlug() {
        return this.subscriptionTierSlug;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetContainerRegistriesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String createdAt;
        private String endpoint;
        private String id;
        private String name;
        private String region;
        private String serverUrl;
        private Integer storageUsageBytes;
        private String subscriptionTierSlug;
        public Builder() {}
        public Builder(GetContainerRegistriesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.createdAt = defaults.createdAt;
    	      this.endpoint = defaults.endpoint;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.region = defaults.region;
    	      this.serverUrl = defaults.serverUrl;
    	      this.storageUsageBytes = defaults.storageUsageBytes;
    	      this.subscriptionTierSlug = defaults.subscriptionTierSlug;
        }

        @CustomType.Setter
        public Builder createdAt(String createdAt) {
            if (createdAt == null) {
              throw new MissingRequiredPropertyException("GetContainerRegistriesResult", "createdAt");
            }
            this.createdAt = createdAt;
            return this;
        }
        @CustomType.Setter
        public Builder endpoint(String endpoint) {
            if (endpoint == null) {
              throw new MissingRequiredPropertyException("GetContainerRegistriesResult", "endpoint");
            }
            this.endpoint = endpoint;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetContainerRegistriesResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetContainerRegistriesResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder region(String region) {
            if (region == null) {
              throw new MissingRequiredPropertyException("GetContainerRegistriesResult", "region");
            }
            this.region = region;
            return this;
        }
        @CustomType.Setter
        public Builder serverUrl(String serverUrl) {
            if (serverUrl == null) {
              throw new MissingRequiredPropertyException("GetContainerRegistriesResult", "serverUrl");
            }
            this.serverUrl = serverUrl;
            return this;
        }
        @CustomType.Setter
        public Builder storageUsageBytes(Integer storageUsageBytes) {
            if (storageUsageBytes == null) {
              throw new MissingRequiredPropertyException("GetContainerRegistriesResult", "storageUsageBytes");
            }
            this.storageUsageBytes = storageUsageBytes;
            return this;
        }
        @CustomType.Setter
        public Builder subscriptionTierSlug(String subscriptionTierSlug) {
            if (subscriptionTierSlug == null) {
              throw new MissingRequiredPropertyException("GetContainerRegistriesResult", "subscriptionTierSlug");
            }
            this.subscriptionTierSlug = subscriptionTierSlug;
            return this;
        }
        public GetContainerRegistriesResult build() {
            final var _resultValue = new GetContainerRegistriesResult();
            _resultValue.createdAt = createdAt;
            _resultValue.endpoint = endpoint;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.region = region;
            _resultValue.serverUrl = serverUrl;
            _resultValue.storageUsageBytes = storageUsageBytes;
            _resultValue.subscriptionTierSlug = subscriptionTierSlug;
            return _resultValue;
        }
    }
}
