// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetDomainsDomain {
    /**
     * @return (Required) The name of the domain.
     * 
     */
    private String name;
    /**
     * @return The TTL of the domain.
     * 
     */
    private Integer ttl;
    /**
     * @return The uniform resource name of the domain
     * 
     */
    private String urn;

    private GetDomainsDomain() {}
    /**
     * @return (Required) The name of the domain.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The TTL of the domain.
     * 
     */
    public Integer ttl() {
        return this.ttl;
    }
    /**
     * @return The uniform resource name of the domain
     * 
     */
    public String urn() {
        return this.urn;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDomainsDomain defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String name;
        private Integer ttl;
        private String urn;
        public Builder() {}
        public Builder(GetDomainsDomain defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.ttl = defaults.ttl;
    	      this.urn = defaults.urn;
        }

        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetDomainsDomain", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder ttl(Integer ttl) {
            if (ttl == null) {
              throw new MissingRequiredPropertyException("GetDomainsDomain", "ttl");
            }
            this.ttl = ttl;
            return this;
        }
        @CustomType.Setter
        public Builder urn(String urn) {
            if (urn == null) {
              throw new MissingRequiredPropertyException("GetDomainsDomain", "urn");
            }
            this.urn = urn;
            return this;
        }
        public GetDomainsDomain build() {
            final var _resultValue = new GetDomainsDomain();
            _resultValue.name = name;
            _resultValue.ttl = ttl;
            _resultValue.urn = urn;
            return _resultValue;
        }
    }
}
