// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.digitalocean.outputs.GetGenaiKnowledgeBasesFilter;
import com.pulumi.digitalocean.outputs.GetGenaiKnowledgeBasesKnowledgeBase;
import com.pulumi.digitalocean.outputs.GetGenaiKnowledgeBasesSort;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class GetGenaiKnowledgeBasesResult {
    private @Nullable List<GetGenaiKnowledgeBasesFilter> filters;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private List<GetGenaiKnowledgeBasesKnowledgeBase> knowledgeBases;
    private @Nullable List<GetGenaiKnowledgeBasesSort> sorts;

    private GetGenaiKnowledgeBasesResult() {}
    public List<GetGenaiKnowledgeBasesFilter> filters() {
        return this.filters == null ? List.of() : this.filters;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public List<GetGenaiKnowledgeBasesKnowledgeBase> knowledgeBases() {
        return this.knowledgeBases;
    }
    public List<GetGenaiKnowledgeBasesSort> sorts() {
        return this.sorts == null ? List.of() : this.sorts;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetGenaiKnowledgeBasesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<GetGenaiKnowledgeBasesFilter> filters;
        private String id;
        private List<GetGenaiKnowledgeBasesKnowledgeBase> knowledgeBases;
        private @Nullable List<GetGenaiKnowledgeBasesSort> sorts;
        public Builder() {}
        public Builder(GetGenaiKnowledgeBasesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.filters = defaults.filters;
    	      this.id = defaults.id;
    	      this.knowledgeBases = defaults.knowledgeBases;
    	      this.sorts = defaults.sorts;
        }

        @CustomType.Setter
        public Builder filters(@Nullable List<GetGenaiKnowledgeBasesFilter> filters) {

            this.filters = filters;
            return this;
        }
        public Builder filters(GetGenaiKnowledgeBasesFilter... filters) {
            return filters(List.of(filters));
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetGenaiKnowledgeBasesResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder knowledgeBases(List<GetGenaiKnowledgeBasesKnowledgeBase> knowledgeBases) {
            if (knowledgeBases == null) {
              throw new MissingRequiredPropertyException("GetGenaiKnowledgeBasesResult", "knowledgeBases");
            }
            this.knowledgeBases = knowledgeBases;
            return this;
        }
        public Builder knowledgeBases(GetGenaiKnowledgeBasesKnowledgeBase... knowledgeBases) {
            return knowledgeBases(List.of(knowledgeBases));
        }
        @CustomType.Setter
        public Builder sorts(@Nullable List<GetGenaiKnowledgeBasesSort> sorts) {

            this.sorts = sorts;
            return this;
        }
        public Builder sorts(GetGenaiKnowledgeBasesSort... sorts) {
            return sorts(List.of(sorts));
        }
        public GetGenaiKnowledgeBasesResult build() {
            final var _resultValue = new GetGenaiKnowledgeBasesResult();
            _resultValue.filters = filters;
            _resultValue.id = id;
            _resultValue.knowledgeBases = knowledgeBases;
            _resultValue.sorts = sorts;
            return _resultValue;
        }
    }
}
