// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetGradientaiKnowledgeBaseIndexingJobsJob {
    /**
     * @return Number of datasources indexed completed
     * 
     */
    private Integer completedDatasources;
    /**
     * @return Creation timestamp
     * 
     */
    private String createdAt;
    /**
     * @return List of data source UUIDs
     * 
     */
    private List<String> dataSourceUuids;
    /**
     * @return Finish timestamp
     * 
     */
    private String finishedAt;
    /**
     * @return Knowledge base UUID
     * 
     */
    private String knowledgeBaseUuid;
    /**
     * @return Current phase of the batch job
     * 
     */
    private String phase;
    /**
     * @return Start timestamp
     * 
     */
    private String startedAt;
    /**
     * @return Status of the indexing job
     * 
     */
    private String status;
    /**
     * @return Number of tokens
     * 
     */
    private Integer tokens;
    /**
     * @return Total number of datasources being indexed
     * 
     */
    private Integer totalDatasources;
    /**
     * @return Total items failed
     * 
     */
    private String totalItemsFailed;
    /**
     * @return Total items indexed
     * 
     */
    private String totalItemsIndexed;
    /**
     * @return Total items skipped
     * 
     */
    private String totalItemsSkipped;
    /**
     * @return Last update timestamp
     * 
     */
    private String updatedAt;
    /**
     * @return Unique identifier of the indexing job
     * 
     */
    private String uuid;

    private GetGradientaiKnowledgeBaseIndexingJobsJob() {}
    /**
     * @return Number of datasources indexed completed
     * 
     */
    public Integer completedDatasources() {
        return this.completedDatasources;
    }
    /**
     * @return Creation timestamp
     * 
     */
    public String createdAt() {
        return this.createdAt;
    }
    /**
     * @return List of data source UUIDs
     * 
     */
    public List<String> dataSourceUuids() {
        return this.dataSourceUuids;
    }
    /**
     * @return Finish timestamp
     * 
     */
    public String finishedAt() {
        return this.finishedAt;
    }
    /**
     * @return Knowledge base UUID
     * 
     */
    public String knowledgeBaseUuid() {
        return this.knowledgeBaseUuid;
    }
    /**
     * @return Current phase of the batch job
     * 
     */
    public String phase() {
        return this.phase;
    }
    /**
     * @return Start timestamp
     * 
     */
    public String startedAt() {
        return this.startedAt;
    }
    /**
     * @return Status of the indexing job
     * 
     */
    public String status() {
        return this.status;
    }
    /**
     * @return Number of tokens
     * 
     */
    public Integer tokens() {
        return this.tokens;
    }
    /**
     * @return Total number of datasources being indexed
     * 
     */
    public Integer totalDatasources() {
        return this.totalDatasources;
    }
    /**
     * @return Total items failed
     * 
     */
    public String totalItemsFailed() {
        return this.totalItemsFailed;
    }
    /**
     * @return Total items indexed
     * 
     */
    public String totalItemsIndexed() {
        return this.totalItemsIndexed;
    }
    /**
     * @return Total items skipped
     * 
     */
    public String totalItemsSkipped() {
        return this.totalItemsSkipped;
    }
    /**
     * @return Last update timestamp
     * 
     */
    public String updatedAt() {
        return this.updatedAt;
    }
    /**
     * @return Unique identifier of the indexing job
     * 
     */
    public String uuid() {
        return this.uuid;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetGradientaiKnowledgeBaseIndexingJobsJob defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer completedDatasources;
        private String createdAt;
        private List<String> dataSourceUuids;
        private String finishedAt;
        private String knowledgeBaseUuid;
        private String phase;
        private String startedAt;
        private String status;
        private Integer tokens;
        private Integer totalDatasources;
        private String totalItemsFailed;
        private String totalItemsIndexed;
        private String totalItemsSkipped;
        private String updatedAt;
        private String uuid;
        public Builder() {}
        public Builder(GetGradientaiKnowledgeBaseIndexingJobsJob defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.completedDatasources = defaults.completedDatasources;
    	      this.createdAt = defaults.createdAt;
    	      this.dataSourceUuids = defaults.dataSourceUuids;
    	      this.finishedAt = defaults.finishedAt;
    	      this.knowledgeBaseUuid = defaults.knowledgeBaseUuid;
    	      this.phase = defaults.phase;
    	      this.startedAt = defaults.startedAt;
    	      this.status = defaults.status;
    	      this.tokens = defaults.tokens;
    	      this.totalDatasources = defaults.totalDatasources;
    	      this.totalItemsFailed = defaults.totalItemsFailed;
    	      this.totalItemsIndexed = defaults.totalItemsIndexed;
    	      this.totalItemsSkipped = defaults.totalItemsSkipped;
    	      this.updatedAt = defaults.updatedAt;
    	      this.uuid = defaults.uuid;
        }

        @CustomType.Setter
        public Builder completedDatasources(Integer completedDatasources) {
            if (completedDatasources == null) {
              throw new MissingRequiredPropertyException("GetGradientaiKnowledgeBaseIndexingJobsJob", "completedDatasources");
            }
            this.completedDatasources = completedDatasources;
            return this;
        }
        @CustomType.Setter
        public Builder createdAt(String createdAt) {
            if (createdAt == null) {
              throw new MissingRequiredPropertyException("GetGradientaiKnowledgeBaseIndexingJobsJob", "createdAt");
            }
            this.createdAt = createdAt;
            return this;
        }
        @CustomType.Setter
        public Builder dataSourceUuids(List<String> dataSourceUuids) {
            if (dataSourceUuids == null) {
              throw new MissingRequiredPropertyException("GetGradientaiKnowledgeBaseIndexingJobsJob", "dataSourceUuids");
            }
            this.dataSourceUuids = dataSourceUuids;
            return this;
        }
        public Builder dataSourceUuids(String... dataSourceUuids) {
            return dataSourceUuids(List.of(dataSourceUuids));
        }
        @CustomType.Setter
        public Builder finishedAt(String finishedAt) {
            if (finishedAt == null) {
              throw new MissingRequiredPropertyException("GetGradientaiKnowledgeBaseIndexingJobsJob", "finishedAt");
            }
            this.finishedAt = finishedAt;
            return this;
        }
        @CustomType.Setter
        public Builder knowledgeBaseUuid(String knowledgeBaseUuid) {
            if (knowledgeBaseUuid == null) {
              throw new MissingRequiredPropertyException("GetGradientaiKnowledgeBaseIndexingJobsJob", "knowledgeBaseUuid");
            }
            this.knowledgeBaseUuid = knowledgeBaseUuid;
            return this;
        }
        @CustomType.Setter
        public Builder phase(String phase) {
            if (phase == null) {
              throw new MissingRequiredPropertyException("GetGradientaiKnowledgeBaseIndexingJobsJob", "phase");
            }
            this.phase = phase;
            return this;
        }
        @CustomType.Setter
        public Builder startedAt(String startedAt) {
            if (startedAt == null) {
              throw new MissingRequiredPropertyException("GetGradientaiKnowledgeBaseIndexingJobsJob", "startedAt");
            }
            this.startedAt = startedAt;
            return this;
        }
        @CustomType.Setter
        public Builder status(String status) {
            if (status == null) {
              throw new MissingRequiredPropertyException("GetGradientaiKnowledgeBaseIndexingJobsJob", "status");
            }
            this.status = status;
            return this;
        }
        @CustomType.Setter
        public Builder tokens(Integer tokens) {
            if (tokens == null) {
              throw new MissingRequiredPropertyException("GetGradientaiKnowledgeBaseIndexingJobsJob", "tokens");
            }
            this.tokens = tokens;
            return this;
        }
        @CustomType.Setter
        public Builder totalDatasources(Integer totalDatasources) {
            if (totalDatasources == null) {
              throw new MissingRequiredPropertyException("GetGradientaiKnowledgeBaseIndexingJobsJob", "totalDatasources");
            }
            this.totalDatasources = totalDatasources;
            return this;
        }
        @CustomType.Setter
        public Builder totalItemsFailed(String totalItemsFailed) {
            if (totalItemsFailed == null) {
              throw new MissingRequiredPropertyException("GetGradientaiKnowledgeBaseIndexingJobsJob", "totalItemsFailed");
            }
            this.totalItemsFailed = totalItemsFailed;
            return this;
        }
        @CustomType.Setter
        public Builder totalItemsIndexed(String totalItemsIndexed) {
            if (totalItemsIndexed == null) {
              throw new MissingRequiredPropertyException("GetGradientaiKnowledgeBaseIndexingJobsJob", "totalItemsIndexed");
            }
            this.totalItemsIndexed = totalItemsIndexed;
            return this;
        }
        @CustomType.Setter
        public Builder totalItemsSkipped(String totalItemsSkipped) {
            if (totalItemsSkipped == null) {
              throw new MissingRequiredPropertyException("GetGradientaiKnowledgeBaseIndexingJobsJob", "totalItemsSkipped");
            }
            this.totalItemsSkipped = totalItemsSkipped;
            return this;
        }
        @CustomType.Setter
        public Builder updatedAt(String updatedAt) {
            if (updatedAt == null) {
              throw new MissingRequiredPropertyException("GetGradientaiKnowledgeBaseIndexingJobsJob", "updatedAt");
            }
            this.updatedAt = updatedAt;
            return this;
        }
        @CustomType.Setter
        public Builder uuid(String uuid) {
            if (uuid == null) {
              throw new MissingRequiredPropertyException("GetGradientaiKnowledgeBaseIndexingJobsJob", "uuid");
            }
            this.uuid = uuid;
            return this;
        }
        public GetGradientaiKnowledgeBaseIndexingJobsJob build() {
            final var _resultValue = new GetGradientaiKnowledgeBaseIndexingJobsJob();
            _resultValue.completedDatasources = completedDatasources;
            _resultValue.createdAt = createdAt;
            _resultValue.dataSourceUuids = dataSourceUuids;
            _resultValue.finishedAt = finishedAt;
            _resultValue.knowledgeBaseUuid = knowledgeBaseUuid;
            _resultValue.phase = phase;
            _resultValue.startedAt = startedAt;
            _resultValue.status = status;
            _resultValue.tokens = tokens;
            _resultValue.totalDatasources = totalDatasources;
            _resultValue.totalItemsFailed = totalItemsFailed;
            _resultValue.totalItemsIndexed = totalItemsIndexed;
            _resultValue.totalItemsSkipped = totalItemsSkipped;
            _resultValue.updatedAt = updatedAt;
            _resultValue.uuid = uuid;
            return _resultValue;
        }
    }
}
