// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.digitalocean.outputs.GetGradientaiCustomModelsCustomModel;
import com.pulumi.digitalocean.outputs.GetGradientaiCustomModelsFilter;
import com.pulumi.digitalocean.outputs.GetGradientaiCustomModelsSort;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetGradientaiCustomModelsResult {
    private List<GetGradientaiCustomModelsCustomModel> customModels;
    private @Nullable List<GetGradientaiCustomModelsFilter> filters;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private @Nullable List<GetGradientaiCustomModelsSort> sorts;
    private @Nullable String status;

    private GetGradientaiCustomModelsResult() {}
    public List<GetGradientaiCustomModelsCustomModel> customModels() {
        return this.customModels;
    }
    public List<GetGradientaiCustomModelsFilter> filters() {
        return this.filters == null ? List.of() : this.filters;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public List<GetGradientaiCustomModelsSort> sorts() {
        return this.sorts == null ? List.of() : this.sorts;
    }
    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetGradientaiCustomModelsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetGradientaiCustomModelsCustomModel> customModels;
        private @Nullable List<GetGradientaiCustomModelsFilter> filters;
        private String id;
        private @Nullable List<GetGradientaiCustomModelsSort> sorts;
        private @Nullable String status;
        public Builder() {}
        public Builder(GetGradientaiCustomModelsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.customModels = defaults.customModels;
    	      this.filters = defaults.filters;
    	      this.id = defaults.id;
    	      this.sorts = defaults.sorts;
    	      this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder customModels(List<GetGradientaiCustomModelsCustomModel> customModels) {
            if (customModels == null) {
              throw new MissingRequiredPropertyException("GetGradientaiCustomModelsResult", "customModels");
            }
            this.customModels = customModels;
            return this;
        }
        public Builder customModels(GetGradientaiCustomModelsCustomModel... customModels) {
            return customModels(List.of(customModels));
        }
        @CustomType.Setter
        public Builder filters(@Nullable List<GetGradientaiCustomModelsFilter> filters) {

            this.filters = filters;
            return this;
        }
        public Builder filters(GetGradientaiCustomModelsFilter... filters) {
            return filters(List.of(filters));
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetGradientaiCustomModelsResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder sorts(@Nullable List<GetGradientaiCustomModelsSort> sorts) {

            this.sorts = sorts;
            return this;
        }
        public Builder sorts(GetGradientaiCustomModelsSort... sorts) {
            return sorts(List.of(sorts));
        }
        @CustomType.Setter
        public Builder status(@Nullable String status) {

            this.status = status;
            return this;
        }
        public GetGradientaiCustomModelsResult build() {
            final var _resultValue = new GetGradientaiCustomModelsResult();
            _resultValue.customModels = customModels;
            _resultValue.filters = filters;
            _resultValue.id = id;
            _resultValue.sorts = sorts;
            _resultValue.status = status;
            return _resultValue;
        }
    }
}
