// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.util.Objects;

@CustomType
public final class KubernetesClusterP2pOciRegistryPlugin {
    /**
     * @return Boolean flag whether the p2p-oci-registry-plugin should be enabled or not.
     * 
     */
    private Boolean enabled;

    private KubernetesClusterP2pOciRegistryPlugin() {}
    /**
     * @return Boolean flag whether the p2p-oci-registry-plugin should be enabled or not.
     * 
     */
    public Boolean enabled() {
        return this.enabled;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(KubernetesClusterP2pOciRegistryPlugin defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean enabled;
        public Builder() {}
        public Builder(KubernetesClusterP2pOciRegistryPlugin defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enabled = defaults.enabled;
        }

        @CustomType.Setter
        public Builder enabled(Boolean enabled) {
            if (enabled == null) {
              throw new MissingRequiredPropertyException("KubernetesClusterP2pOciRegistryPlugin", "enabled");
            }
            this.enabled = enabled;
            return this;
        }
        public KubernetesClusterP2pOciRegistryPlugin build() {
            final var _resultValue = new KubernetesClusterP2pOciRegistryPlugin();
            _resultValue.enabled = enabled;
            return _resultValue;
        }
    }
}
