// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class MicrovmSource {
    /**
     * @return The ID of a checkpoint to restore.
     * 
     */
    private @Nullable String checkpointId;
    /**
     * @return The OCI reference of the workload container image, such as `docker.io/library/nginx:latest`.
     * 
     */
    private @Nullable String ociRef;

    private MicrovmSource() {}
    /**
     * @return The ID of a checkpoint to restore.
     * 
     */
    public Optional<String> checkpointId() {
        return Optional.ofNullable(this.checkpointId);
    }
    /**
     * @return The OCI reference of the workload container image, such as `docker.io/library/nginx:latest`.
     * 
     */
    public Optional<String> ociRef() {
        return Optional.ofNullable(this.ociRef);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(MicrovmSource defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String checkpointId;
        private @Nullable String ociRef;
        public Builder() {}
        public Builder(MicrovmSource defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.checkpointId = defaults.checkpointId;
    	      this.ociRef = defaults.ociRef;
        }

        @CustomType.Setter
        public Builder checkpointId(@Nullable String checkpointId) {

            this.checkpointId = checkpointId;
            return this;
        }
        @CustomType.Setter
        public Builder ociRef(@Nullable String ociRef) {

            this.ociRef = ociRef;
            return this;
        }
        public MicrovmSource build() {
            final var _resultValue = new MicrovmSource();
            _resultValue.checkpointId = checkpointId;
            _resultValue.ociRef = ociRef;
            return _resultValue;
        }
    }
}
