// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AgentPlatformAgentChildAgentApiKeyArgs extends com.pulumi.resources.ResourceArgs {

    public static final AgentPlatformAgentChildAgentApiKeyArgs Empty = new AgentPlatformAgentChildAgentApiKeyArgs();

    /**
     * API Key value
     * 
     */
    @Import(name="apiKey")
    private @Nullable Output<String> apiKey;

    /**
     * @return API Key value
     * 
     */
    public Optional<Output<String>> apiKey() {
        return Optional.ofNullable(this.apiKey);
    }

    private AgentPlatformAgentChildAgentApiKeyArgs() {}

    private AgentPlatformAgentChildAgentApiKeyArgs(AgentPlatformAgentChildAgentApiKeyArgs $) {
        this.apiKey = $.apiKey;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AgentPlatformAgentChildAgentApiKeyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AgentPlatformAgentChildAgentApiKeyArgs $;

        public Builder() {
            $ = new AgentPlatformAgentChildAgentApiKeyArgs();
        }

        public Builder(AgentPlatformAgentChildAgentApiKeyArgs defaults) {
            $ = new AgentPlatformAgentChildAgentApiKeyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param apiKey API Key value
         * 
         * @return builder
         * 
         */
        public Builder apiKey(@Nullable Output<String> apiKey) {
            $.apiKey = apiKey;
            return this;
        }

        /**
         * @param apiKey API Key value
         * 
         * @return builder
         * 
         */
        public Builder apiKey(String apiKey) {
            return apiKey(Output.of(apiKey));
        }

        public AgentPlatformAgentChildAgentApiKeyArgs build() {
            return $;
        }
    }

}
