// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.digitalocean.inputs.AppSpecServiceLogDestinationDatadogArgs;
import com.pulumi.digitalocean.inputs.AppSpecServiceLogDestinationLogtailArgs;
import com.pulumi.digitalocean.inputs.AppSpecServiceLogDestinationOpenSearchArgs;
import com.pulumi.digitalocean.inputs.AppSpecServiceLogDestinationPapertrailArgs;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AppSpecServiceLogDestinationArgs extends com.pulumi.resources.ResourceArgs {

    public static final AppSpecServiceLogDestinationArgs Empty = new AppSpecServiceLogDestinationArgs();

    /**
     * Datadog configuration.
     * 
     */
    @Import(name="datadog")
    private @Nullable Output<AppSpecServiceLogDestinationDatadogArgs> datadog;

    /**
     * @return Datadog configuration.
     * 
     */
    public Optional<Output<AppSpecServiceLogDestinationDatadogArgs>> datadog() {
        return Optional.ofNullable(this.datadog);
    }

    /**
     * Logtail configuration.
     * 
     */
    @Import(name="logtail")
    private @Nullable Output<AppSpecServiceLogDestinationLogtailArgs> logtail;

    /**
     * @return Logtail configuration.
     * 
     */
    public Optional<Output<AppSpecServiceLogDestinationLogtailArgs>> logtail() {
        return Optional.ofNullable(this.logtail);
    }

    /**
     * Name of the log destination. Minimum length: 2. Maximum length: 42.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Name of the log destination. Minimum length: 2. Maximum length: 42.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * OpenSearch configuration.
     * 
     */
    @Import(name="openSearch")
    private @Nullable Output<AppSpecServiceLogDestinationOpenSearchArgs> openSearch;

    /**
     * @return OpenSearch configuration.
     * 
     */
    public Optional<Output<AppSpecServiceLogDestinationOpenSearchArgs>> openSearch() {
        return Optional.ofNullable(this.openSearch);
    }

    /**
     * Papertrail configuration.
     * 
     */
    @Import(name="papertrail")
    private @Nullable Output<AppSpecServiceLogDestinationPapertrailArgs> papertrail;

    /**
     * @return Papertrail configuration.
     * 
     */
    public Optional<Output<AppSpecServiceLogDestinationPapertrailArgs>> papertrail() {
        return Optional.ofNullable(this.papertrail);
    }

    private AppSpecServiceLogDestinationArgs() {}

    private AppSpecServiceLogDestinationArgs(AppSpecServiceLogDestinationArgs $) {
        this.datadog = $.datadog;
        this.logtail = $.logtail;
        this.name = $.name;
        this.openSearch = $.openSearch;
        this.papertrail = $.papertrail;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AppSpecServiceLogDestinationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AppSpecServiceLogDestinationArgs $;

        public Builder() {
            $ = new AppSpecServiceLogDestinationArgs();
        }

        public Builder(AppSpecServiceLogDestinationArgs defaults) {
            $ = new AppSpecServiceLogDestinationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param datadog Datadog configuration.
         * 
         * @return builder
         * 
         */
        public Builder datadog(@Nullable Output<AppSpecServiceLogDestinationDatadogArgs> datadog) {
            $.datadog = datadog;
            return this;
        }

        /**
         * @param datadog Datadog configuration.
         * 
         * @return builder
         * 
         */
        public Builder datadog(AppSpecServiceLogDestinationDatadogArgs datadog) {
            return datadog(Output.of(datadog));
        }

        /**
         * @param logtail Logtail configuration.
         * 
         * @return builder
         * 
         */
        public Builder logtail(@Nullable Output<AppSpecServiceLogDestinationLogtailArgs> logtail) {
            $.logtail = logtail;
            return this;
        }

        /**
         * @param logtail Logtail configuration.
         * 
         * @return builder
         * 
         */
        public Builder logtail(AppSpecServiceLogDestinationLogtailArgs logtail) {
            return logtail(Output.of(logtail));
        }

        /**
         * @param name Name of the log destination. Minimum length: 2. Maximum length: 42.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the log destination. Minimum length: 2. Maximum length: 42.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param openSearch OpenSearch configuration.
         * 
         * @return builder
         * 
         */
        public Builder openSearch(@Nullable Output<AppSpecServiceLogDestinationOpenSearchArgs> openSearch) {
            $.openSearch = openSearch;
            return this;
        }

        /**
         * @param openSearch OpenSearch configuration.
         * 
         * @return builder
         * 
         */
        public Builder openSearch(AppSpecServiceLogDestinationOpenSearchArgs openSearch) {
            return openSearch(Output.of(openSearch));
        }

        /**
         * @param papertrail Papertrail configuration.
         * 
         * @return builder
         * 
         */
        public Builder papertrail(@Nullable Output<AppSpecServiceLogDestinationPapertrailArgs> papertrail) {
            $.papertrail = papertrail;
            return this;
        }

        /**
         * @param papertrail Papertrail configuration.
         * 
         * @return builder
         * 
         */
        public Builder papertrail(AppSpecServiceLogDestinationPapertrailArgs papertrail) {
            return papertrail(Output.of(papertrail));
        }

        public AppSpecServiceLogDestinationArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("AppSpecServiceLogDestinationArgs", "name");
            }
            return $;
        }
    }

}
