// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.digitalocean.inputs.GetGenaiAgentVersionsFilterArgs;
import com.pulumi.digitalocean.inputs.GetGenaiAgentVersionsSortArgs;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetGenaiAgentVersionsArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetGenaiAgentVersionsArgs Empty = new GetGenaiAgentVersionsArgs();

    @Import(name="agentId", required=true)
    private Output<String> agentId;

    public Output<String> agentId() {
        return this.agentId;
    }

    @Import(name="filters")
    private @Nullable Output<List<GetGenaiAgentVersionsFilterArgs>> filters;

    public Optional<Output<List<GetGenaiAgentVersionsFilterArgs>>> filters() {
        return Optional.ofNullable(this.filters);
    }

    @Import(name="sorts")
    private @Nullable Output<List<GetGenaiAgentVersionsSortArgs>> sorts;

    public Optional<Output<List<GetGenaiAgentVersionsSortArgs>>> sorts() {
        return Optional.ofNullable(this.sorts);
    }

    private GetGenaiAgentVersionsArgs() {}

    private GetGenaiAgentVersionsArgs(GetGenaiAgentVersionsArgs $) {
        this.agentId = $.agentId;
        this.filters = $.filters;
        this.sorts = $.sorts;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetGenaiAgentVersionsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetGenaiAgentVersionsArgs $;

        public Builder() {
            $ = new GetGenaiAgentVersionsArgs();
        }

        public Builder(GetGenaiAgentVersionsArgs defaults) {
            $ = new GetGenaiAgentVersionsArgs(Objects.requireNonNull(defaults));
        }

        public Builder agentId(Output<String> agentId) {
            $.agentId = agentId;
            return this;
        }

        public Builder agentId(String agentId) {
            return agentId(Output.of(agentId));
        }

        public Builder filters(@Nullable Output<List<GetGenaiAgentVersionsFilterArgs>> filters) {
            $.filters = filters;
            return this;
        }

        public Builder filters(List<GetGenaiAgentVersionsFilterArgs> filters) {
            return filters(Output.of(filters));
        }

        public Builder filters(GetGenaiAgentVersionsFilterArgs... filters) {
            return filters(List.of(filters));
        }

        public Builder sorts(@Nullable Output<List<GetGenaiAgentVersionsSortArgs>> sorts) {
            $.sorts = sorts;
            return this;
        }

        public Builder sorts(List<GetGenaiAgentVersionsSortArgs> sorts) {
            return sorts(Output.of(sorts));
        }

        public Builder sorts(GetGenaiAgentVersionsSortArgs... sorts) {
            return sorts(List.of(sorts));
        }

        public GetGenaiAgentVersionsArgs build() {
            if ($.agentId == null) {
                throw new MissingRequiredPropertyException("GetGenaiAgentVersionsArgs", "agentId");
            }
            return $;
        }
    }

}
