// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetGradientaiAgentModelVersion extends com.pulumi.resources.InvokeArgs {

    public static final GetGradientaiAgentModelVersion Empty = new GetGradientaiAgentModelVersion();

    /**
     * Major version of the model
     * 
     */
    @Import(name="major")
    private @Nullable Integer major;

    /**
     * @return Major version of the model
     * 
     */
    public Optional<Integer> major() {
        return Optional.ofNullable(this.major);
    }

    /**
     * Minor version of the model
     * 
     */
    @Import(name="minor")
    private @Nullable Integer minor;

    /**
     * @return Minor version of the model
     * 
     */
    public Optional<Integer> minor() {
        return Optional.ofNullable(this.minor);
    }

    /**
     * Patch version of the model
     * 
     */
    @Import(name="patch")
    private @Nullable Integer patch;

    /**
     * @return Patch version of the model
     * 
     */
    public Optional<Integer> patch() {
        return Optional.ofNullable(this.patch);
    }

    private GetGradientaiAgentModelVersion() {}

    private GetGradientaiAgentModelVersion(GetGradientaiAgentModelVersion $) {
        this.major = $.major;
        this.minor = $.minor;
        this.patch = $.patch;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetGradientaiAgentModelVersion defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetGradientaiAgentModelVersion $;

        public Builder() {
            $ = new GetGradientaiAgentModelVersion();
        }

        public Builder(GetGradientaiAgentModelVersion defaults) {
            $ = new GetGradientaiAgentModelVersion(Objects.requireNonNull(defaults));
        }

        /**
         * @param major Major version of the model
         * 
         * @return builder
         * 
         */
        public Builder major(@Nullable Integer major) {
            $.major = major;
            return this;
        }

        /**
         * @param minor Minor version of the model
         * 
         * @return builder
         * 
         */
        public Builder minor(@Nullable Integer minor) {
            $.minor = minor;
            return this;
        }

        /**
         * @param patch Patch version of the model
         * 
         * @return builder
         * 
         */
        public Builder patch(@Nullable Integer patch) {
            $.patch = patch;
            return this;
        }

        public GetGradientaiAgentModelVersion build() {
            return $;
        }
    }

}
