// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.util.Objects;


public final class GetKubernetesClusterAmdGpuDraDriverArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetKubernetesClusterAmdGpuDraDriverArgs Empty = new GetKubernetesClusterAmdGpuDraDriverArgs();

    @Import(name="enabled", required=true)
    private Output<Boolean> enabled;

    public Output<Boolean> enabled() {
        return this.enabled;
    }

    private GetKubernetesClusterAmdGpuDraDriverArgs() {}

    private GetKubernetesClusterAmdGpuDraDriverArgs(GetKubernetesClusterAmdGpuDraDriverArgs $) {
        this.enabled = $.enabled;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetKubernetesClusterAmdGpuDraDriverArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetKubernetesClusterAmdGpuDraDriverArgs $;

        public Builder() {
            $ = new GetKubernetesClusterAmdGpuDraDriverArgs();
        }

        public Builder(GetKubernetesClusterAmdGpuDraDriverArgs defaults) {
            $ = new GetKubernetesClusterAmdGpuDraDriverArgs(Objects.requireNonNull(defaults));
        }

        public Builder enabled(Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        public GetKubernetesClusterAmdGpuDraDriverArgs build() {
            if ($.enabled == null) {
                throw new MissingRequiredPropertyException("GetKubernetesClusterAmdGpuDraDriverArgs", "enabled");
            }
            return $;
        }
    }

}
