// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOcean.Outputs
{

    [OutputType]
    public sealed class DropletAutoscaleDropletTemplate
    {
        /// <summary>
        /// Image slug of the Droplet Autoscale pool underlying resource(s).
        /// </summary>
        public readonly string Image;
        /// <summary>
        /// Boolean flag to enable IPv6 networking on the Droplet Autoscale pool underlying resource(s).
        /// </summary>
        public readonly bool? Ipv6;
        /// <summary>
        /// Project UUID to create the Droplet Autoscale pool underlying resource(s).
        /// </summary>
        public readonly string? ProjectId;
        /// <summary>
        /// Region slug of the Droplet Autoscale pool underlying resource(s).
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// Size slug of the Droplet Autoscale pool underlying resource(s).
        /// </summary>
        public readonly string Size;
        /// <summary>
        /// SSH fingerprints to add to the Droplet Autoscale pool underlying resource(s).
        /// </summary>
        public readonly ImmutableArray<string> SshKeys;
        /// <summary>
        /// List of tags to add to the Droplet Autoscale pool underlying resource(s).
        /// </summary>
        public readonly ImmutableArray<string> Tags;
        /// <summary>
        /// Custom user data that can be added to the Droplet Autoscale pool underlying resource(s). This can be a 
        /// cloud init script that user may configure to setup their application workload.
        /// </summary>
        public readonly string? UserData;
        /// <summary>
        /// VPC UUID to create the Droplet Autoscale pool underlying resource(s). If not provided, this is inferred
        /// from the specified `region` (default VPC).
        /// </summary>
        public readonly string? VpcUuid;
        /// <summary>
        /// Boolean flag to enable metric agent on the Droplet Autoscale pool underlying resource(s). The
        /// metric agent enables collecting resource utilization metrics, which allows making resource based scaling decisions.
        /// </summary>
        public readonly bool? WithDropletAgent;

        [OutputConstructor]
        private DropletAutoscaleDropletTemplate(
            string image,

            bool? ipv6,

            string? projectId,

            string region,

            string size,

            ImmutableArray<string> sshKeys,

            ImmutableArray<string> tags,

            string? userData,

            string? vpcUuid,

            bool? withDropletAgent)
        {
            Image = image;
            Ipv6 = ipv6;
            ProjectId = projectId;
            Region = region;
            Size = size;
            SshKeys = sshKeys;
            Tags = tags;
            UserData = userData;
            VpcUuid = vpcUuid;
            WithDropletAgent = withDropletAgent;
        }
    }
}
