// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOcean.Outputs
{

    [OutputType]
    public sealed class GetAppSpecWorkerAutoscalingMetricsResult
    {
        /// <summary>
        /// Settings for scaling the component based on CPU utilization.
        /// </summary>
        public readonly Outputs.GetAppSpecWorkerAutoscalingMetricsCpuResult? Cpu;

        [OutputConstructor]
        private GetAppSpecWorkerAutoscalingMetricsResult(Outputs.GetAppSpecWorkerAutoscalingMetricsCpuResult? cpu)
        {
            Cpu = cpu;
        }
    }
}
