// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOcean.Outputs
{

    [OutputType]
    public sealed class GetDedicatedInferenceSizesSizeResult
    {
        /// <summary>
        /// The number of vCPUs.
        /// </summary>
        public readonly int Cpu;
        /// <summary>
        /// The currency for the price.
        /// </summary>
        public readonly string Currency;
        /// <summary>
        /// The disks attached to this size. Each element contains:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDedicatedInferenceSizesSizeDiskResult> Disks;
        /// <summary>
        /// The slug identifier for this GPU size.
        /// </summary>
        public readonly string GpuSlug;
        /// <summary>
        /// GPU hardware details. Each element contains:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDedicatedInferenceSizesSizeGpusResult> Gpus;
        /// <summary>
        /// The amount of memory in MiB.
        /// </summary>
        public readonly int Memory;
        /// <summary>
        /// The hourly price for this GPU size.
        /// </summary>
        public readonly string PricePerHour;
        /// <summary>
        /// The regions where this GPU size is available.
        /// </summary>
        public readonly ImmutableArray<string> Regions;
        /// <summary>
        /// The category this size belongs to. Each element contains:
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDedicatedInferenceSizesSizeSizeCategoryResult> SizeCategories;

        [OutputConstructor]
        private GetDedicatedInferenceSizesSizeResult(
            int cpu,

            string currency,

            ImmutableArray<Outputs.GetDedicatedInferenceSizesSizeDiskResult> disks,

            string gpuSlug,

            ImmutableArray<Outputs.GetDedicatedInferenceSizesSizeGpusResult> gpus,

            int memory,

            string pricePerHour,

            ImmutableArray<string> regions,

            ImmutableArray<Outputs.GetDedicatedInferenceSizesSizeSizeCategoryResult> sizeCategories)
        {
            Cpu = cpu;
            Currency = currency;
            Disks = disks;
            GpuSlug = gpuSlug;
            Gpus = gpus;
            Memory = memory;
            PricePerHour = pricePerHour;
            Regions = regions;
            SizeCategories = sizeCategories;
        }
    }
}
