// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOcean.Outputs
{

    [OutputType]
    public sealed class GetLoadBalancerGlbSettingCdnResult
    {
        /// <summary>
        /// cache enable flag
        /// </summary>
        public readonly bool IsEnabled;

        [OutputConstructor]
        private GetLoadBalancerGlbSettingCdnResult(bool isEnabled)
        {
            IsEnabled = isEnabled;
        }
    }
}
