// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.digitalocean.GenaiIndexingJobCancelArgs;
import com.pulumi.digitalocean.Utilities;
import com.pulumi.digitalocean.inputs.GenaiIndexingJobCancelState;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

/**
 * @deprecated
 * digitalocean.GenaiIndexingJobCancel has been deprecated in favor of digitalocean.GradientaiIndexingJobCancel
 * 
 */
@Deprecated /* digitalocean.GenaiIndexingJobCancel has been deprecated in favor of digitalocean.GradientaiIndexingJobCancel */
@ResourceType(type="digitalocean:index/genaiIndexingJobCancel:GenaiIndexingJobCancel")
public class GenaiIndexingJobCancel extends com.pulumi.resources.CustomResource {
    /**
     * Number of data sources that were completed before cancellation.
     * 
     */
    @Export(name="completedDatasources", refs={Integer.class}, tree="[0]")
    private Output<Integer> completedDatasources;

    /**
     * @return Number of data sources that were completed before cancellation.
     * 
     */
    public Output<Integer> completedDatasources() {
        return this.completedDatasources;
    }
    /**
     * When the indexing job was created.
     * 
     */
    @Export(name="createdAt", refs={String.class}, tree="[0]")
    private Output<String> createdAt;

    /**
     * @return When the indexing job was created.
     * 
     */
    public Output<String> createdAt() {
        return this.createdAt;
    }
    /**
     * List of data source UUIDs associated with this indexing job.
     * 
     */
    @Export(name="dataSourceUuids", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> dataSourceUuids;

    /**
     * @return List of data source UUIDs associated with this indexing job.
     * 
     */
    public Output<List<String>> dataSourceUuids() {
        return this.dataSourceUuids;
    }
    /**
     * When the indexing job was finished.
     * 
     */
    @Export(name="finishedAt", refs={String.class}, tree="[0]")
    private Output<String> finishedAt;

    /**
     * @return When the indexing job was finished.
     * 
     */
    public Output<String> finishedAt() {
        return this.finishedAt;
    }
    /**
     * The UUID of the knowledge base associated with this indexing job.
     * 
     */
    @Export(name="knowledgeBaseUuid", refs={String.class}, tree="[0]")
    private Output<String> knowledgeBaseUuid;

    /**
     * @return The UUID of the knowledge base associated with this indexing job.
     * 
     */
    public Output<String> knowledgeBaseUuid() {
        return this.knowledgeBaseUuid;
    }
    /**
     * Current phase of the indexing job.
     * 
     */
    @Export(name="phase", refs={String.class}, tree="[0]")
    private Output<String> phase;

    /**
     * @return Current phase of the indexing job.
     * 
     */
    public Output<String> phase() {
        return this.phase;
    }
    /**
     * When the indexing job was started.
     * 
     */
    @Export(name="startedAt", refs={String.class}, tree="[0]")
    private Output<String> startedAt;

    /**
     * @return When the indexing job was started.
     * 
     */
    public Output<String> startedAt() {
        return this.startedAt;
    }
    /**
     * The status of the indexing job after cancellation.
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return The status of the indexing job after cancellation.
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * Number of tokens processed before cancellation.
     * 
     */
    @Export(name="tokens", refs={Integer.class}, tree="[0]")
    private Output<Integer> tokens;

    /**
     * @return Number of tokens processed before cancellation.
     * 
     */
    public Output<Integer> tokens() {
        return this.tokens;
    }
    /**
     * Total number of data sources in the indexing job.
     * 
     */
    @Export(name="totalDatasources", refs={Integer.class}, tree="[0]")
    private Output<Integer> totalDatasources;

    /**
     * @return Total number of data sources in the indexing job.
     * 
     */
    public Output<Integer> totalDatasources() {
        return this.totalDatasources;
    }
    /**
     * Total number of items that failed during indexing.
     * 
     */
    @Export(name="totalItemsFailed", refs={Integer.class}, tree="[0]")
    private Output<Integer> totalItemsFailed;

    /**
     * @return Total number of items that failed during indexing.
     * 
     */
    public Output<Integer> totalItemsFailed() {
        return this.totalItemsFailed;
    }
    /**
     * Total number of items that were successfully indexed.
     * 
     */
    @Export(name="totalItemsIndexed", refs={Integer.class}, tree="[0]")
    private Output<Integer> totalItemsIndexed;

    /**
     * @return Total number of items that were successfully indexed.
     * 
     */
    public Output<Integer> totalItemsIndexed() {
        return this.totalItemsIndexed;
    }
    /**
     * Total number of items that were skipped during indexing.
     * 
     */
    @Export(name="totalItemsSkipped", refs={Integer.class}, tree="[0]")
    private Output<Integer> totalItemsSkipped;

    /**
     * @return Total number of items that were skipped during indexing.
     * 
     */
    public Output<Integer> totalItemsSkipped() {
        return this.totalItemsSkipped;
    }
    /**
     * When the indexing job was last updated.
     * 
     */
    @Export(name="updatedAt", refs={String.class}, tree="[0]")
    private Output<String> updatedAt;

    /**
     * @return When the indexing job was last updated.
     * 
     */
    public Output<String> updatedAt() {
        return this.updatedAt;
    }
    /**
     * The UUID of the indexing job to cancel.
     * 
     */
    @Export(name="uuid", refs={String.class}, tree="[0]")
    private Output<String> uuid;

    /**
     * @return The UUID of the indexing job to cancel.
     * 
     */
    public Output<String> uuid() {
        return this.uuid;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public GenaiIndexingJobCancel(java.lang.String name) {
        this(name, GenaiIndexingJobCancelArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public GenaiIndexingJobCancel(java.lang.String name, GenaiIndexingJobCancelArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public GenaiIndexingJobCancel(java.lang.String name, GenaiIndexingJobCancelArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("digitalocean:index/genaiIndexingJobCancel:GenaiIndexingJobCancel", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private GenaiIndexingJobCancel(java.lang.String name, Output<java.lang.String> id, @Nullable GenaiIndexingJobCancelState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("digitalocean:index/genaiIndexingJobCancel:GenaiIndexingJobCancel", name, state, makeResourceOptions(options, id), false);
    }

    private static GenaiIndexingJobCancelArgs makeArgs(GenaiIndexingJobCancelArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? GenaiIndexingJobCancelArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static GenaiIndexingJobCancel get(java.lang.String name, Output<java.lang.String> id, @Nullable GenaiIndexingJobCancelState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new GenaiIndexingJobCancel(name, id, state, options);
    }
}
