// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.digitalocean;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class SpacesBucketPolicyArgs extends com.pulumi.resources.ResourceArgs {

    public static final SpacesBucketPolicyArgs Empty = new SpacesBucketPolicyArgs();

    /**
     * The name of the bucket to which to apply the policy.
     * 
     */
    @Import(name="bucket", required=true)
    private Output<String> bucket;

    /**
     * @return The name of the bucket to which to apply the policy.
     * 
     */
    public Output<String> bucket() {
        return this.bucket;
    }

    /**
     * The text of the policy.
     * 
     */
    @Import(name="policy", required=true)
    private Output<String> policy;

    /**
     * @return The text of the policy.
     * 
     */
    public Output<String> policy() {
        return this.policy;
    }

    /**
     * The region where the bucket resides.
     * 
     */
    @Import(name="region", required=true)
    private Output<String> region;

    /**
     * @return The region where the bucket resides.
     * 
     */
    public Output<String> region() {
        return this.region;
    }

    private SpacesBucketPolicyArgs() {}

    private SpacesBucketPolicyArgs(SpacesBucketPolicyArgs $) {
        this.bucket = $.bucket;
        this.policy = $.policy;
        this.region = $.region;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SpacesBucketPolicyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SpacesBucketPolicyArgs $;

        public Builder() {
            $ = new SpacesBucketPolicyArgs();
        }

        public Builder(SpacesBucketPolicyArgs defaults) {
            $ = new SpacesBucketPolicyArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param bucket The name of the bucket to which to apply the policy.
         * 
         * @return builder
         * 
         */
        public Builder bucket(Output<String> bucket) {
            $.bucket = bucket;
            return this;
        }

        /**
         * @param bucket The name of the bucket to which to apply the policy.
         * 
         * @return builder
         * 
         */
        public Builder bucket(String bucket) {
            return bucket(Output.of(bucket));
        }

        /**
         * @param policy The text of the policy.
         * 
         * @return builder
         * 
         */
        public Builder policy(Output<String> policy) {
            $.policy = policy;
            return this;
        }

        /**
         * @param policy The text of the policy.
         * 
         * @return builder
         * 
         */
        public Builder policy(String policy) {
            return policy(Output.of(policy));
        }

        /**
         * @param region The region where the bucket resides.
         * 
         * @return builder
         * 
         */
        public Builder region(Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region The region where the bucket resides.
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        public SpacesBucketPolicyArgs build() {
            $.bucket = Objects.requireNonNull($.bucket, "expected parameter 'bucket' to be non-null");
            $.policy = Objects.requireNonNull($.policy, "expected parameter 'policy' to be non-null");
            $.region = Objects.requireNonNull($.region, "expected parameter 'region' to be non-null");
            return $;
        }
    }

}
