// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOcean.Inputs
{

    public sealed class GetProjectsSortInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The sort direction. This may be either `Asc` or `Desc`.
        /// </summary>
        [Input("direction")]
        public Input<string>? Direction { get; set; }

        /// <summary>
        /// Sort the projects by this key. This may be one of `Name`,
        /// `Purpose`, `Description`, or `Environment`.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        public GetProjectsSortInputArgs()
        {
        }
        public static new GetProjectsSortInputArgs Empty => new GetProjectsSortInputArgs();
    }
}
