// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOcean.Inputs
{

    public sealed class KubernetesClusterSsoArgs : global::Pulumi.ResourceArgs
    {
        [Input("clientId")]
        public Input<string>? ClientId { get; set; }

        /// <summary>
        /// Boolean flag whether the component is enabled or not.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        [Input("issuerUrl")]
        public Input<string>? IssuerUrl { get; set; }

        [Input("required")]
        public Input<bool>? Required { get; set; }

        public KubernetesClusterSsoArgs()
        {
        }
        public static new KubernetesClusterSsoArgs Empty => new KubernetesClusterSsoArgs();
    }
}
