// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DigitalOcean.Inputs
{

    public sealed class NfsAccessPointAccessPolicyGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Anonymous GID mapped for NFS clients. Defaults to `65534`.
        /// </summary>
        [Input("anongid")]
        public Input<int>? Anongid { get; set; }

        /// <summary>
        /// Anonymous UID mapped for NFS clients. Defaults to `65534`.
        /// </summary>
        [Input("anonuid")]
        public Input<int>? Anonuid { get; set; }

        /// <summary>
        /// Whether identity enforcement is enabled. Defaults to `False`.
        /// </summary>
        [Input("identityEnforcementEnabled")]
        public Input<bool>? IdentityEnforcementEnabled { get; set; }

        [Input("protocols")]
        private InputList<string>? _protocols;

        /// <summary>
        /// List of NFS protocols. Defaults to `["NFS4"]`.
        /// </summary>
        public InputList<string> Protocols
        {
            get => _protocols ?? (_protocols = new InputList<string>());
            set => _protocols = value;
        }

        /// <summary>
        /// Squash configuration. Valid values are `NO_SQUASH`, `ROOT_SQUASH`, and `ALL_SQUASH`. Defaults to `ROOT_SQUASH`.
        /// </summary>
        [Input("squashConfig")]
        public Input<string>? SquashConfig { get; set; }

        public NfsAccessPointAccessPolicyGetArgs()
        {
        }
        public static new NfsAccessPointAccessPolicyGetArgs Empty => new NfsAccessPointAccessPolicyGetArgs();
    }
}
