// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * Provides a DigitalOcean Dedicated Inference resource. This can be used to create,
 * modify, and delete dedicated inference endpoints for running GPU-accelerated
 * model inference.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as digitalocean from "@pulumi/digitalocean";
 *
 * const example = new digitalocean.DedicatedInference("example", {
 *     name: "my-inference-endpoint",
 *     region: "tor1",
 *     modelDeployments: [{
 *         modelSlug: "deepseek-r1-distill-qwen-14b",
 *         modelProvider: "digitalocean",
 *         accelerators: [{
 *             acceleratorSlug: "gpu-h100x1-80gb",
 *             scale: 1,
 *             type: "nvidia_h100",
 *         }],
 *     }],
 * });
 * ```
 *
 * ### With Public Endpoint
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as digitalocean from "@pulumi/digitalocean";
 *
 * const _public = new digitalocean.DedicatedInference("public", {
 *     name: "my-public-inference",
 *     region: "tor1",
 *     enablePublicEndpoint: true,
 *     modelDeployments: [{
 *         modelSlug: "deepseek-r1-distill-qwen-14b",
 *         modelProvider: "digitalocean",
 *         accelerators: [{
 *             acceleratorSlug: "gpu-h100x1-80gb",
 *             scale: 1,
 *             type: "nvidia_h100",
 *         }],
 *     }],
 * });
 * ```
 *
 * ### With VPC
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as digitalocean from "@pulumi/digitalocean";
 *
 * const _private = new digitalocean.DedicatedInference("private", {
 *     name: "my-private-inference",
 *     region: "tor1",
 *     vpcUuid: example.id,
 *     modelDeployments: [{
 *         modelSlug: "deepseek-r1-distill-qwen-14b",
 *         modelProvider: "digitalocean",
 *         accelerators: [{
 *             acceleratorSlug: "gpu-h100x1-80gb",
 *             scale: 1,
 *             type: "nvidia_h100",
 *         }],
 *     }],
 * });
 * ```
 *
 * ## Import
 *
 * Dedicated inference endpoints can be imported using their `id`, e.g.
 *
 * ```sh
 * $ pulumi import digitalocean:index/dedicatedInference:DedicatedInference example endpoint-id
 * ```
 */
export class DedicatedInference extends pulumi.CustomResource {
    /**
     * Get an existing DedicatedInference resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DedicatedInferenceState, opts?: pulumi.CustomResourceOptions): DedicatedInference {
        return new DedicatedInference(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'digitalocean:index/dedicatedInference:DedicatedInference';

    /**
     * Returns true if the given object is an instance of DedicatedInference.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DedicatedInference {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DedicatedInference.__pulumiType;
    }

    /**
     * The date and time when the dedicated inference endpoint was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Whether to enable a public HTTPS endpoint for the dedicated inference endpoint. Defaults to `false`. This field is immutable after creation and changing it forces a new resource.
     */
    declare public readonly enablePublicEndpoint: pulumi.Output<boolean | undefined>;
    /**
     * A HuggingFace token for accessing gated models.
     */
    declare public readonly huggingFaceToken: pulumi.Output<string | undefined>;
    /**
     * The list of model deployments to run on the dedicated inference endpoint. Each `modelDeployments` block supports:
     */
    declare public readonly modelDeployments: pulumi.Output<outputs.DedicatedInferenceModelDeployment[]>;
    /**
     * A human-readable name for the dedicated inference endpoint.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The fully-qualified domain name of the private endpoint.
     */
    declare public /*out*/ readonly privateEndpointFqdn: pulumi.Output<string>;
    /**
     * The fully-qualified domain name of the public endpoint, if enabled.
     */
    declare public /*out*/ readonly publicEndpointFqdn: pulumi.Output<string>;
    /**
     * The region slug where the dedicated inference endpoint will be deployed. Changing this forces a new resource.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The current status of the dedicated inference endpoint.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * The date and time when the dedicated inference endpoint was last updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * The UUID of the VPC to deploy the dedicated inference endpoint into. Changing this forces a new resource.
     */
    declare public readonly vpcUuid: pulumi.Output<string | undefined>;

    /**
     * Create a DedicatedInference resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DedicatedInferenceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DedicatedInferenceArgs | DedicatedInferenceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DedicatedInferenceState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["enablePublicEndpoint"] = state?.enablePublicEndpoint;
            resourceInputs["huggingFaceToken"] = state?.huggingFaceToken;
            resourceInputs["modelDeployments"] = state?.modelDeployments;
            resourceInputs["name"] = state?.name;
            resourceInputs["privateEndpointFqdn"] = state?.privateEndpointFqdn;
            resourceInputs["publicEndpointFqdn"] = state?.publicEndpointFqdn;
            resourceInputs["region"] = state?.region;
            resourceInputs["status"] = state?.status;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["vpcUuid"] = state?.vpcUuid;
        } else {
            const args = argsOrState as DedicatedInferenceArgs | undefined;
            if (args?.modelDeployments === undefined && !opts.urn) {
                throw new Error("Missing required property 'modelDeployments'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["enablePublicEndpoint"] = args?.enablePublicEndpoint;
            resourceInputs["huggingFaceToken"] = args?.huggingFaceToken ? pulumi.secret(args.huggingFaceToken) : undefined;
            resourceInputs["modelDeployments"] = args?.modelDeployments;
            resourceInputs["name"] = args?.name;
            resourceInputs["region"] = args?.region;
            resourceInputs["vpcUuid"] = args?.vpcUuid;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["privateEndpointFqdn"] = undefined /*out*/;
            resourceInputs["publicEndpointFqdn"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["huggingFaceToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(DedicatedInference.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DedicatedInference resources.
 */
export interface DedicatedInferenceState {
    /**
     * The date and time when the dedicated inference endpoint was created.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * Whether to enable a public HTTPS endpoint for the dedicated inference endpoint. Defaults to `false`. This field is immutable after creation and changing it forces a new resource.
     */
    enablePublicEndpoint?: pulumi.Input<boolean | undefined>;
    /**
     * A HuggingFace token for accessing gated models.
     */
    huggingFaceToken?: pulumi.Input<string | undefined>;
    /**
     * The list of model deployments to run on the dedicated inference endpoint. Each `modelDeployments` block supports:
     */
    modelDeployments?: pulumi.Input<pulumi.Input<inputs.DedicatedInferenceModelDeployment>[] | undefined>;
    /**
     * A human-readable name for the dedicated inference endpoint.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The fully-qualified domain name of the private endpoint.
     */
    privateEndpointFqdn?: pulumi.Input<string | undefined>;
    /**
     * The fully-qualified domain name of the public endpoint, if enabled.
     */
    publicEndpointFqdn?: pulumi.Input<string | undefined>;
    /**
     * The region slug where the dedicated inference endpoint will be deployed. Changing this forces a new resource.
     */
    region?: pulumi.Input<string | undefined>;
    /**
     * The current status of the dedicated inference endpoint.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * The date and time when the dedicated inference endpoint was last updated.
     */
    updatedAt?: pulumi.Input<string | undefined>;
    /**
     * The UUID of the VPC to deploy the dedicated inference endpoint into. Changing this forces a new resource.
     */
    vpcUuid?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a DedicatedInference resource.
 */
export interface DedicatedInferenceArgs {
    /**
     * Whether to enable a public HTTPS endpoint for the dedicated inference endpoint. Defaults to `false`. This field is immutable after creation and changing it forces a new resource.
     */
    enablePublicEndpoint?: pulumi.Input<boolean | undefined>;
    /**
     * A HuggingFace token for accessing gated models.
     */
    huggingFaceToken?: pulumi.Input<string | undefined>;
    /**
     * The list of model deployments to run on the dedicated inference endpoint. Each `modelDeployments` block supports:
     */
    modelDeployments: pulumi.Input<pulumi.Input<inputs.DedicatedInferenceModelDeployment>[]>;
    /**
     * A human-readable name for the dedicated inference endpoint.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The region slug where the dedicated inference endpoint will be deployed. Changing this forces a new resource.
     */
    region: pulumi.Input<string>;
    /**
     * The UUID of the VPC to deploy the dedicated inference endpoint into. Changing this forces a new resource.
     */
    vpcUuid?: pulumi.Input<string | undefined>;
}
