// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

export function getAgentPlatformKnowledgeBases(args?: GetAgentPlatformKnowledgeBasesArgs, opts?: pulumi.InvokeOptions): Promise<GetAgentPlatformKnowledgeBasesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("digitalocean:index/getAgentPlatformKnowledgeBases:getAgentPlatformKnowledgeBases", {
        "filters": args.filters,
        "sorts": args.sorts,
    }, opts);
}

/**
 * A collection of arguments for invoking getAgentPlatformKnowledgeBases.
 */
export interface GetAgentPlatformKnowledgeBasesArgs {
    filters?: inputs.GetAgentPlatformKnowledgeBasesFilter[];
    sorts?: inputs.GetAgentPlatformKnowledgeBasesSort[];
}

/**
 * A collection of values returned by getAgentPlatformKnowledgeBases.
 */
export interface GetAgentPlatformKnowledgeBasesResult {
    readonly filters?: outputs.GetAgentPlatformKnowledgeBasesFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly knowledgeBases: outputs.GetAgentPlatformKnowledgeBasesKnowledgeBase[];
    readonly sorts?: outputs.GetAgentPlatformKnowledgeBasesSort[];
}
export function getAgentPlatformKnowledgeBasesOutput(args?: GetAgentPlatformKnowledgeBasesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAgentPlatformKnowledgeBasesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("digitalocean:index/getAgentPlatformKnowledgeBases:getAgentPlatformKnowledgeBases", {
        "filters": args.filters,
        "sorts": args.sorts,
    }, opts);
}

/**
 * A collection of arguments for invoking getAgentPlatformKnowledgeBases.
 */
export interface GetAgentPlatformKnowledgeBasesOutputArgs {
    filters?: pulumi.Input<pulumi.Input<inputs.GetAgentPlatformKnowledgeBasesFilterArgs>[] | undefined>;
    sorts?: pulumi.Input<pulumi.Input<inputs.GetAgentPlatformKnowledgeBasesSortArgs>[] | undefined>;
}
