// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

export function getAgentPlatformCustomModel(args: GetAgentPlatformCustomModelArgs, opts?: pulumi.InvokeOptions): Promise<GetAgentPlatformCustomModelResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("digitalocean:index/getAgentPlatformCustomModel:getAgentPlatformCustomModel", {
        "uuid": args.uuid,
    }, opts);
}

/**
 * A collection of arguments for invoking getAgentPlatformCustomModel.
 */
export interface GetAgentPlatformCustomModelArgs {
    uuid: string;
}

/**
 * A collection of values returned by getAgentPlatformCustomModel.
 */
export interface GetAgentPlatformCustomModelResult {
    readonly activeDeployments: outputs.GetAgentPlatformCustomModelActiveDeployment[];
    readonly architecture: string;
    readonly contextLength: number;
    readonly costEstimatePerMonth: number;
    readonly createdAt: string;
    readonly description: string;
    readonly errorMessage: string;
    readonly fileCount: number;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly inputModalities: string[];
    readonly license: string;
    readonly name: string;
    readonly outputModalities: string[];
    readonly parameters: string;
    readonly sourceReves: outputs.GetAgentPlatformCustomModelSourceRef[];
    readonly sourceType: string;
    readonly status: string;
    readonly storageRegion: string;
    readonly tags: string[];
    readonly teamId: string;
    readonly totalSizeBytes: string;
    readonly updatedAt: string;
    readonly uuid: string;
}
export function getAgentPlatformCustomModelOutput(args: GetAgentPlatformCustomModelOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAgentPlatformCustomModelResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("digitalocean:index/getAgentPlatformCustomModel:getAgentPlatformCustomModel", {
        "uuid": args.uuid,
    }, opts);
}

/**
 * A collection of arguments for invoking getAgentPlatformCustomModel.
 */
export interface GetAgentPlatformCustomModelOutputArgs {
    uuid: pulumi.Input<string>;
}
