// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

export function getGradientaiAgentVersions(args: GetGradientaiAgentVersionsArgs, opts?: pulumi.InvokeOptions): Promise<GetGradientaiAgentVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("digitalocean:index/getGradientaiAgentVersions:getGradientaiAgentVersions", {
        "agentId": args.agentId,
        "filters": args.filters,
        "sorts": args.sorts,
    }, opts);
}

/**
 * A collection of arguments for invoking getGradientaiAgentVersions.
 */
export interface GetGradientaiAgentVersionsArgs {
    agentId: string;
    filters?: inputs.GetGradientaiAgentVersionsFilter[];
    sorts?: inputs.GetGradientaiAgentVersionsSort[];
}

/**
 * A collection of values returned by getGradientaiAgentVersions.
 */
export interface GetGradientaiAgentVersionsResult {
    readonly agentId: string;
    readonly agentVersions: outputs.GetGradientaiAgentVersionsAgentVersion[];
    readonly filters?: outputs.GetGradientaiAgentVersionsFilter[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly sorts?: outputs.GetGradientaiAgentVersionsSort[];
}
export function getGradientaiAgentVersionsOutput(args: GetGradientaiAgentVersionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetGradientaiAgentVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("digitalocean:index/getGradientaiAgentVersions:getGradientaiAgentVersions", {
        "agentId": args.agentId,
        "filters": args.filters,
        "sorts": args.sorts,
    }, opts);
}

/**
 * A collection of arguments for invoking getGradientaiAgentVersions.
 */
export interface GetGradientaiAgentVersionsOutputArgs {
    agentId: pulumi.Input<string>;
    filters?: pulumi.Input<pulumi.Input<inputs.GetGradientaiAgentVersionsFilterArgs>[]>;
    sorts?: pulumi.Input<pulumi.Input<inputs.GetGradientaiAgentVersionsSortArgs>[]>;
}
