// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * Provides a DigitalOcean vector database resource. Vector databases are powered by
 * [Weaviate](https://weaviate.io/) and are managed independently from standard
 * managed database clusters.
 *
 * ## Example Usage
 *
 * ### Create a new vector database
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as digitalocean from "@pulumi/digitalocean";
 *
 * const example = new digitalocean.VectorDatabase("example", {
 *     name: "example-vector-db",
 *     region: "nyc1",
 *     size: "db-s-1vcpu-1gb",
 *     tags: ["production"],
 * });
 * ```
 *
 * ### Create a vector database with advanced configuration
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as digitalocean from "@pulumi/digitalocean";
 *
 * const example = new digitalocean.VectorDatabase("example", {
 *     name: "example-vector-db",
 *     region: "nyc1",
 *     size: "db-s-2vcpu-2gb",
 *     config: {
 *         defaultQuantization: "none",
 *         enableAutoSchema: true,
 *         weaviateVersion: "1.25.0",
 *     },
 * });
 * ```
 *
 * ## Import
 *
 * Vector databases can be imported using their `id`, e.g.
 *
 * ```sh
 * $ pulumi import digitalocean:index/vectorDatabase:VectorDatabase example 245bcfd0-7f31-4ce6-a2bc-475a116cca97
 * ```
 */
export class VectorDatabase extends pulumi.CustomResource {
    /**
     * Get an existing VectorDatabase resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VectorDatabaseState, opts?: pulumi.CustomResourceOptions): VectorDatabase {
        return new VectorDatabase(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'digitalocean:index/vectorDatabase:VectorDatabase';

    /**
     * Returns true if the given object is an instance of VectorDatabase.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VectorDatabase {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VectorDatabase.__pulumiType;
    }

    /**
     * Advanced configuration for the vector database. The structure is documented below.
     */
    declare public readonly config: pulumi.Output<outputs.VectorDatabaseConfig>;
    /**
     * The date and time when the vector database was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The connection endpoints for the vector database. The structure is documented below.
     */
    declare public /*out*/ readonly endpoints: pulumi.Output<outputs.VectorDatabaseEndpoint[]>;
    /**
     * The name of the vector database. Changing this forces a new resource to be created.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The UUID of the account that owns the vector database.
     */
    declare public /*out*/ readonly ownerUuid: pulumi.Output<string>;
    /**
     * The ID of the project that the vector database is assigned to. If excluded, the database will be assigned to your default project. Changing this forces a new resource to be created.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * The slug identifier for the region where the vector database will be created (ex. `nyc1`). Changing this forces a new resource to be created.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The slug identifier representing the size of the vector database (ex. `db-s-1vcpu-1gb`).
     */
    declare public readonly size: pulumi.Output<string>;
    /**
     * The current status of the vector database (ex. `active`).
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * A list of tag names to be applied to the vector database.
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    /**
     * The date and time when the vector database was last updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a VectorDatabase resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VectorDatabaseArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VectorDatabaseArgs | VectorDatabaseState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VectorDatabaseState | undefined;
            resourceInputs["config"] = state?.config;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["endpoints"] = state?.endpoints;
            resourceInputs["name"] = state?.name;
            resourceInputs["ownerUuid"] = state?.ownerUuid;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["region"] = state?.region;
            resourceInputs["size"] = state?.size;
            resourceInputs["status"] = state?.status;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as VectorDatabaseArgs | undefined;
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            if (args?.size === undefined && !opts.urn) {
                throw new Error("Missing required property 'size'");
            }
            resourceInputs["config"] = args?.config;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["region"] = args?.region;
            resourceInputs["size"] = args?.size;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["endpoints"] = undefined /*out*/;
            resourceInputs["ownerUuid"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VectorDatabase.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VectorDatabase resources.
 */
export interface VectorDatabaseState {
    /**
     * Advanced configuration for the vector database. The structure is documented below.
     */
    config?: pulumi.Input<inputs.VectorDatabaseConfig | undefined>;
    /**
     * The date and time when the vector database was created.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * The connection endpoints for the vector database. The structure is documented below.
     */
    endpoints?: pulumi.Input<pulumi.Input<inputs.VectorDatabaseEndpoint>[] | undefined>;
    /**
     * The name of the vector database. Changing this forces a new resource to be created.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The UUID of the account that owns the vector database.
     */
    ownerUuid?: pulumi.Input<string | undefined>;
    /**
     * The ID of the project that the vector database is assigned to. If excluded, the database will be assigned to your default project. Changing this forces a new resource to be created.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * The slug identifier for the region where the vector database will be created (ex. `nyc1`). Changing this forces a new resource to be created.
     */
    region?: pulumi.Input<string | undefined>;
    /**
     * The slug identifier representing the size of the vector database (ex. `db-s-1vcpu-1gb`).
     */
    size?: pulumi.Input<string | undefined>;
    /**
     * The current status of the vector database (ex. `active`).
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * A list of tag names to be applied to the vector database.
     */
    tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The date and time when the vector database was last updated.
     */
    updatedAt?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a VectorDatabase resource.
 */
export interface VectorDatabaseArgs {
    /**
     * Advanced configuration for the vector database. The structure is documented below.
     */
    config?: pulumi.Input<inputs.VectorDatabaseConfig | undefined>;
    /**
     * The name of the vector database. Changing this forces a new resource to be created.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the project that the vector database is assigned to. If excluded, the database will be assigned to your default project. Changing this forces a new resource to be created.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * The slug identifier for the region where the vector database will be created (ex. `nyc1`). Changing this forces a new resource to be created.
     */
    region: pulumi.Input<string>;
    /**
     * The slug identifier representing the size of the vector database (ex. `db-s-1vcpu-1gb`).
     */
    size: pulumi.Input<string>;
    /**
     * A list of tag names to be applied to the vector database.
     */
    tags?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}
