name: Upload bin assets
description: Uploads the provider and tfgen binaries to `bin/`.

runs:
  using: "composite"
  steps:
    - name: Tar provider binaries
      shell: bash
      run: tar -zcf ${{ github.workspace }}/bin/provider.tar.gz -C ${{ github.workspace }}/bin/ pulumi-resource-digitalocean pulumi-tfgen-digitalocean
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: digitalocean-provider.tar.gz
        path: ${{ github.workspace }}/bin/provider.tar.gz
        retention-days: 30
